### ISSUE TITLE
The previous error was related to the duplicated parameter "perf3_udp_duration_2 "

### ISSUE THREAD

**Issue by wifinigel** [wifinigel/wiperf_poller#13]
pi@raspberrypiredewifi:~ $ sudo /usr/bin/python3 /usr/share/wiperf/wiperf_run.py
Traceback (most recent call last):
  File "/usr/share/wiperf/wiperf_run.py", line 4, in <module>
    import wiperf_poller.__main__ as agent
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 63, in <module>
    config_vars = read_local_config(config_file, file_logger)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/helpers/config.py", line 24, in read_local_config
    config.read(config_file)
  File "/usr/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/etc/wiperf/config.ini' [line 343]: option 'iperf3_udp_duration_2' in section 'Iperf3_udp_test' already exists

On config.ini file:
[Iperf3_udp_test]
; yes = enabled, no =

**Comment by wifinigel** [comment]
My bad, I had already hit & fixed this issue, but not pushed the updated config.ini file to GitHub. Should be fixed now. Sorry for this.

**Comment by lealog** [comment]
tested and it's OK
