### ISSUE TITLE
Management interface using ZeroTier with error - Unknown status: UNKNOWN (should be 'UP' or 'DOWN')

### ISSUE THREAD

**Issue by lealog** [wifinigel/wiperf_poller#17]
Hi,

I'm testing V3 and tried to configure the management interface using ZeroTier.
Default settings:
; -------------mgt interface parameters ------------
; interface name over which mgt traffic is sent (i.e. how we get to our management
; server) - options: wlan0, eth0, ztxxxxxx (ZeroTier), lo (local instance of Influx)
mgt_if: ztukutsbw2
; ---------------------------------------------------

;-------------- InFlux1 Config ---------------
; IP address (ipv4 or ipv6) or hostname of InfluxDB host
influx_host: 192.168.192.104
; IP version used to communicate with server: "ipv4" or "ipv6"
influx_host_ip_type: ipv4
; InfluxDb collector port (8086 by default)
influx_port: 8086
influx_ssl: True
influx_username: xxxx
influx_password: xxxx
influx_database: xxxx
;---------------------------------------------

Using these settings, I'm seeing that wiperf has the following problem.

2021-03-20 01:05:59,242 - Probe_Log - INFO - ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
2021-03-20 01:05:59,242 - Probe_Log - INFO -    Reporting/mgt server connectivty checks.
2021-03-20 01:05:59,242 - Probe_Log - INFO - ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
2021-03-20 01:05:59,264 - Probe_Log - ERROR - Unknown status: UNKNOWN (should be 'UP' or 'DOWN')

/usr/bin/python3 /usr/share/wiperf/wiperf_run.py
Traceback (most recent call last):
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 264, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 211, in main
    mgt_connection_obj.check_mgt_connection(lockf_obj, watchdog_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/mgtconnectiontester.py", line 225, in check_mgt_connection
    if not mgt_interface_obj.interface_up():
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/helpers/networkadapter.py", line 93, in interface_up
    raise ValueError(err_string)
ValueError: Unknown status: UNKNOWN (should be 'UP' or 'DOWN')

**Comment by wifinigel** [comment]
Thanks for this report. I must admit I have not tested with ZeroTier during the V3 dev work.

Under investigation.

**Comment by wifinigel** [comment]
Issue found to be extraction of interface status info from ip link cmd.

Issue now fixed/tested and fixed files pushed to dev branch of repo.

**Comment by lealog** [comment]
tested and it's OK
